name: Terraform CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-scan:
    name: Terraform CI & Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: enviroment/dev

    steps:

      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 4. Terraform Init
      # No Azure authentication required for validation
      - name: Terraform Init
        run: terraform init -backend=false

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Install TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      # 7. TFLint
      - name: Run TFLint
        run: |
          tflint --init
          tflint

      # 8. Trivy Security Scan
      - name: Run Trivy Terraform Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1